// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx4uxWAeu-yV9xwiSwo_aKed4G8rYXxS4',
    appId: '1:491617653071:web:94a866640f352aac99b53a',
    messagingSenderId: '491617653071',
    projectId: 'telegram-clone-dd51d',
    authDomain: 'telegram-clone-dd51d.firebaseapp.com',
    storageBucket: 'telegram-clone-dd51d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOK8kt-K615a7euStIvef6o9_tOrV8c-M',
    appId: '1:491617653071:android:9811d039740cd98b99b53a',
    messagingSenderId: '491617653071',
    projectId: 'telegram-clone-dd51d',
    storageBucket: 'telegram-clone-dd51d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfr9nUpHSIEwagdv65YRJe9SqMUU0_K3k',
    appId: '1:491617653071:ios:f6d6a5b74486fe8899b53a',
    messagingSenderId: '491617653071',
    projectId: 'telegram-clone-dd51d',
    storageBucket: 'telegram-clone-dd51d.firebasestorage.app',
    iosBundleId: 'com.softsolutions.telegram',
  );
}
